apiVersion: v1
kind: Template
metadata:
  annotations:
    description: sample app build config setup
  name: sample-go-app-builds
message: "Use the following template to create buildconfig and imageStream for builds triggered from cicd namespaces "
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: sample-go-app
    name: sample-go-app
    namespace: build
  spec:
    lookupPolicy:
        local: false 
    tags:
      - annotations: null
        from:
          kind: DockerImage
          name: image-registry.openshift-image-registry.svc:5000/build/sample-go-app:latest
        generation: 3
        importPolicy: {}
        name: latest
        referencePolicy:
          type: Source
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: sample-go-app
    namespace: build
  spec:
    source:
      type: Binary
    strategy:
      type: Docker
      dockerStrategy:
        noCache: true
    output:
      to:
        kind: ImageStreamTag
        name: 'image-registry.openshift-image-registry.svc:5000/build/sample-go-app:latest'

