apiVersion: v1
kind: Template
metadata:
  annotations:
    description: sample app build config setup
  name: sample-go-app-builds
message: "Use the following template to create buildconfig and imageStream for builds triggered from cicd namespaces "
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: sample-go-app
    name: sample-go-app
    namespace: build
  spec:
      failedBuildsHistroyLimit: 5
      ndoeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: sample-go-app:v1
      postcommit: {}
      resource: {}
      runPolicy: Serial
      source:
        binary: {}
        type: Docker
    triggers:
      - github:
          secret: 
          type: Github
      - generic:
          secret: 
          type: Generic
- apiVersion: v1
  kind: imageStream
  metadata:
    labels:
      build: sample-go-app
    name: sample-go-app
    namespace: build
  spec:
    lookupPolicy:
        local: false 
    tags:
      - annotations: null
        from:
          kind: DockerImage
          name: sample-go-app:latest
        generation: 3
        importPolicy: {}
        name: latest
        referencePolicy:
          type: Source

