apiVersion: v1
kind: Template
metadata:
  annotations:
    description: sample app build config setup
  name: sample-go-app-builds
message: "Use the following template to create buildconfig and imageStream for builds triggered from cicd namespaces "
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: sample-go-app
    name: sample-go-app
    namespace: build
  spec:
    lookupPolicy:
        local: false 
    tags:
      - annotations: null
        from:
          kind: DockerImage
          name: sample-go-app:latest
        generation: 3
        importPolicy: {}
        name: latest
        referencePolicy:
          type: Source
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: "sample-go-app" 
  spec:
    runPolicy: "Serial" 
    triggers: 
      - type: "GitHub"
        github:
          secret: "github"
      - type: "Generic"
        generic:
    source: 
      git:
        ref: develop
        uri: "https://github.com/sankamath/sample-go-app"
    strategy: 
      strategy:
        dockerStrategy:
          dockerfilePath: base/Dockerfile
    output: 
      to:
        kind: "ImageStreamTag"
        name: "sample-go-app:v1"
