kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "pipeline-develop"
spec:
  successfulBuildsHistoryLimit: 10
  failedBuildsHistoryLimit: 10
  source:
    git:
      ref: develop
      uri: 'https://github.com/sankamath/sample-go-app'
    sourceSecret:
      name: cicd-cred
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      env:
        - name: GIT_SSL_NO_VERIFY
          value: 'true'
      jenkinsfilePath: pipeline/Jenkinsfile
    type: JenkinsPipeline
  triggers:
    - github:
        secret: cicd-cred
      type: GitHub
