apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonLabels:
  app: sample-go-app
  env: st
  release: 1.0.0

#nameSuffix: -st

#deployment patch with container names, main container env options
patchesStrategicMerge:
- patch-deploy.yaml

configMapGenerator:
- files:
  - app.properties
  name: app-config

patches:
- patch: |-
    - op: replace
      path: /spec/host
      value: sample-go-app-st.apps.test
    - op: replace
      path: /spec/to/name
      value: sample-go-app
  target:
    kind: Route
    name: sample-go-app

- patch: |-
    - op: replace
      path: /spec/selector/env
      value: st
  target:
    kind: Service
    name: sample-go-app
- patch: |-
    - op: replace
      path: /spec/type
      value: ClusterIP
  target:
    kind: Service
    name: sample-go-app
